const siteContent = {
  brand: { name: 'BORCELLE', descriptor: 'FASHION' },
  announcement: 'Sign up and get 10% off on your first order',
  navigation: {
    clothing: 'CLOTHING',
    collections: 'COLLECTIONS',
    newArrivals: 'NEW ARRIVALS',
    partyShop: 'PARTY SHOP',
    workwear: 'WORKWEAR',
    giftCard: 'GIFT CARD',
    sale: 'SALE',
    shopBySize: 'SHOP BY SIZE',
    bestSellers: 'BEST SELLERS',
    clothingItems: ['Dresses', 'Tops', 'Shirts', 'Blazers & Jackets', 'T-Shirts', 'Jumpsuits & Rompers', 'Skirts', 'Jeans', 'Shorts', 'Blazers & Pants'],
    collectionItems: ['Work Wear', 'Everyday Edits', 'Cotton', 'Tshirts', 'Party Wear', 'Linen', 'Denims'],
  },
  heroSlides: [
    { image: '/images/Head%20Image%201.png', alt: 'Latest Borcelle fashion collection', eyebrow: 'THE BORCELLE EDIT', title: 'NEW ARRIVALS', subtitle: 'T-SHIRT COLLECTION', action: 'SHOP NOW', category: 'T-Shirts', theme: '' },
    { image: '/images/Head%20Image%202.png', alt: 'A light and elegant Borcelle look', eyebrow: 'EFFORTLESS ELEGANCE', title: 'A SOFTER KIND OF STATEMENT', subtitle: 'Style that speaks softly yet shines boldly.', action: 'SHOP NOW', category: 'Dresses', theme: 'soft' },
    { image: '/images/Head%20Image%203.png', alt: 'A floral ensemble from Borcelle Fashion', eyebrow: 'BORCELLE FASHION', title: 'ELEGANT FLORAL ENSEMBLE', subtitle: 'Timeless elegance through modern design.', action: 'GET OFFER', category: 'Dresses', theme: 'dark' },
  ],
  categoryTiles: [
    { label: 'TOPS', image: '/images/Tops%20Head.png', alt: 'Borcelle tops collection', category: 'Tops' },
    { label: 'DRESSES', image: '/images/Dress%20Head.png', alt: 'Borcelle dresses collection', category: 'Dresses' },
    { label: 'T-SHIRTS', image: '/images/T%20Shirts%20Head.png', alt: 'Borcelle T-shirts collection', category: 'T-Shirts' },
    { label: 'BLAZERS', image: '/images/Blazers%20Head.png', alt: 'Borcelle blazers collection', category: 'Blazers' },
  ],
  promotions: [
    { eyebrow: 'Dresses For Every Occasion', title: 'UNIQUE & COLORFUL STYLES', description: 'Essential Styles Come Alive in Bright Colors', action: 'SHOP NOW', image: '/images/Shop%20Now.png', alt: 'A dress styled for a special occasion', category: 'Dresses' },
    { eyebrow: 'DISCOVER THEM ALL', title: 'STYLES THAT WORK', description: 'WORK WEAR COLLECTION', action: 'FIND MORE', image: '/images/Find%20More.png', alt: 'Modern everyday style', category: 'Blazers' },
  ],
  pages: {
    partyShop: { title: 'PARTY SHOP', description: 'Find a look for every celebration, from elegant evenings to special days.' },
    workwear: { title: 'WORKWEAR', description: 'Polished blazers and easy-to-style pieces for your working wardrobe.' },
    sale: { title: 'SALE', description: 'Explore selected styles and current offers from the Borcelle collection.' },
    giftCard: {
      eyebrow: 'BORCELLE GIFT CARD', title: 'A thoughtful gift, every time.',
      image: '/images/Shop%20Now.png', alt: 'A Borcelle outfit chosen for a special occasion',
      caption: 'Give them a little style.',
      description: 'Digital gift cards are coming soon. In the meantime, explore the collection and find a look to love.',
      action: 'EXPLORE NEW ARRIVALS',
    },
  },
  footer: {
    newsletterTitle: 'Newsletter subscription',
    newsletterDescription: 'Sign up for Borcelle updates to receive information about new arrivals, offers & promos.',
    hotlineTitle: 'ONLINE - CUSTOMER CARE HOTLINE',
    hotlinePhone: '077 ### ###',
    hotlineHours: 'Monday - Friday: 10.00 AM- 5.30 PM',
    email: 'info@borcelle.lk',
    storeTitle: 'BORCELLE FASHION STORE',
    storeAddress: 'No. 17, Charles Drive, Colombo 03.',
    storePhone: '011 ### ## ##',
    storeHours: 'Everyday 10.00 AM - 8.00 PM',
    outletTitle: 'BORCELLE OUTLET HOMAGAMA',
    outletAddress: 'No. 238, Colombo Road, Homagama.',
    outletPhone: '0## ### ###',
    outletHours: 'Everyday 10.00 AM - 8.00 PM',
    quickLinksTitle: 'QUICK LINKS',
    quickLinks: ['About Us', 'FAQ', 'Size Guide', 'International Shipping', 'Exchange Policy', 'Bank Offers', 'Contact Us', 'Privacy Policy', 'Terms of Use'],
  },
}

export default siteContent